- hosts: localhost
  gather_facts: no

  tasks:
  - name: Download vagrant
    become: yes
    get_url:
      url: "https://releases.hashicorp.com/vagrant/1.9.8/vagrant_1.9.8_x86_64.deb"
      dest: .
      

  - name: Install vagrant
    shell: dpkg -i vagrant_1.9.8_x86_64.deb

   
  - name: Do a vagrant init
    command: vagrant init ubuntu/trusty32



  - name: Edit the Vagrantfile
    blockinfile: 
      path: ./Vagrantfile
      block: |
        config.vm.provider "virtualbox" do |vb|
          #   # Display the VirtualBox GUI when booting the machine
          #   vb.gui = true
          vb.cpus = 1
          # change the network card hardware for better performance
          vb.customize ["modifyvm", :id, "--nictype1", "virtio" ]
          vb.customize ["modifyvm", :id, "--nictype2", "virtio" ]

          # suggested fix for slow network performance
          # see https://github.com/mitchellh/vagrant/issues/1807
          vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
          vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
          #   # Customize the amount of memory on the VM:
          vb.memory = "512"
          config.vm.provision :ansible do |ansible|
            ansible.playbook = "provisionCheckbox.yml"
          end
          
        end
  
      insertafter: '#.*Example.*for.*VirtualBox:'

  - name: Do a vagrant up
    command: vagrant up

    

