- hosts: localhost
  gather_facts: no

  tasks:
  - name: Add oracle VB official repository
    lineinfile: 
      path: /etc/apt/sources.list
      line: "deb http://download.virtualbox.org/virtualbox/debian trusty contrib"
      

  - name: adding key
    apt_key: 
      url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc" 
      state: present
  - name: adding another key
    apt_key: 
      url: "https://www.virtualbox.org/download/oracle_vbox.asc"
      state: present

  - name: update
    apt:
      update_cache: yes

  - name: Install virtualbox
    apt:
      name: virtualbox-5.0


  - name: Add users to virtualbox
    shell: usermod -aG vboxusers $USER

  - name: status vbox
    service: 
      name: vboxdrv
      state: started
  - name: install vagrant from deb
    apt:
      deb: https://releases.hashicorp.com/vagrant/1.9.8/vagrant_1.9.8_x86_64.deb?_ga=2.127681869.1728430659.1504721252-1913439545.1503595309

   
  - name: Do a vagrant init
    command: vagrant init ubuntu/trusty32



  - name: Edit the Vagrantfile
    blockinfile: 
      path: ./Vagrantfile
      block: |
        config.vm.provider "virtualbox" do |vb|
          #   # Display the VirtualBox GUI when booting the machine
          #   vb.gui = true
          vb.cpus = 1
          # change the network card hardware for better performance
          vb.customize ["modifyvm", :id, "--nictype1", "virtio" ]
          vb.customize ["modifyvm", :id, "--nictype2", "virtio" ]

          # suggested fix for slow network performance
          # see https://github.com/mitchellh/vagrant/issues/1807
          vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
          vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
          #   # Customize the amount of memory on the VM:
          vb.memory = "512"
          config.vm.provision :ansible do |ansible|
            ansible.playbook = "provisionCheckbox.yml"
          end
          
        end
  
      insertafter: '#.*Example.*for.*VirtualBox:'

  - name: Do a vagrant up
    command: vagrant up

    

