---
- hosts: localhost
  connection: local
  serial: 1
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:  
    - include: tasks/droplet.yml



- hosts: newdroplets
  become: yes
  user: root      
  vars_files:
    - vars.yml
  tasks:
    - include: tasks/checkbox.yml
               

