
- name: Install pip
  become: yes
  apt: 
    name: python-pip
    state: present

- name: Install dopy
  pip:
    name: dopy

- name: Install six
  pip:
    name: six
    
- name: Upgrade pip module dopy
  become: yes
  command: pip install dopy --upgrade
  
- name: Upgrade pip module six
  become: yes
  command: pip install six --upgrade

- name: Getting public key
  command: cat /var/lib/jenkins/.ssh/id_rsa
  register: private_key
  
- name: Deploy public key
  digital_ocean: >
    state=present
    command=ssh
    name=my_ssh_key
    api_token="{{ api_key }}"
    ssh_pub_key= "{{my_pub_key}}"
  register: do_droplet
     
- name: Create Digital Ocean droplet 512Mb/Ubuntu16.04 LTS/Amsterdam
  digital_ocean: >   
    state=present
    command=droplet
    name="{{ do_hostname }}"
    api_token="{{ api_key }}"
    size_id=512mb
    ssh_key_ids="{{ do_droplet.ssh_key.id }}"
    region_id=nyc1
    image_id=ubuntu-16-04-x64
    wait_timeout=600
  register: do_droplet

- debug: msg="ID is {{ do_droplet.droplet.id }}"
- debug: msg="IP is {{ do_droplet.droplet.ip_address }}"
    
- name: Add new droplet to inventory
  add_host: >
    name="{{ do_droplet.droplet.ip_address }}"
    groups=newdroplets
    ansible_python_interpreter=/usr/bin/python3
    ansible_ssh_user=root
    ansible_ssh_private_key_file={{private_key}}
    
- name: Wait for VM to come up
  local_action: wait_for host="{{ do_droplet.droplet.ip_address }}" state=started
  async: no    
- name: ensure droplet exists
  digital_ocean: >
    state=present
    command=droplet
    api_token="{{ api_key }}"
    name="{{ do_hostname }}"
    unique_name=yes
    size_id=512mb
    region_id=nyc1
    image_id=ubuntu-16-04-x64
          
