- name: pwd
  shell: pwd
  register: out

- name: debug
  debug:
    msg: "{{out.stdout}}"

- name: Update all packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - nginx
    - mongodb
    - nodejs-legacy
    - python3-pip

- name: install pymongo
  pip:
    name: pymongo
    state: present

- name: add mongo user
  mongodb_user:
    database: admin
    name: mongo
    password: mongo
    roles: userAdminAnyDatabase
    state: present
  #when: first_run|changed

- name: Restart mongo
  service:
    name: mongodb
    state: restarted
  #when: first_run|changed

- name: clone checkbox repo
  git:
    repo: https://github.com/thegreyd/checkbox.io
    dest: /home/ubuntu/checkbox
    force: yes
    update: yes

- name: configure nginx defaults
  copy:
    src: /home/ubuntu/checkbox/local-conf/default
    dest: /etc/nginx/sites-available/default
    force: yes
    remote_src: True
  #when: first_run|changed 

- name: configure nginx conf
  copy:
    src: /home/ubuntu/checkbox/local-conf/nginx.conf
    dest: /etc/nginx/nginx.conf
    force: yes
    remote_src: True
  #when: first_run|changed   

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  #when: first_run|changed

- name: npm install
  npm:
    path: /home/ubuntu/checkbox/server-side/site/
    state: present

- name: start node server
  environment: 
    MONGO_PORT: 3002
    MONGO_IP: localhost
    MONGO_USER: mongo
    MONGO_PASSWORD: mongo
  shell: node server.js
  async: 2592000
  poll: 0
  args:
    chdir: /home/ubuntu/checkbox/server-side/site/
